name: Storybook Deployment
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: storybook
    env:
      working-directory: ./docs
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pre Build
        run: yarn && yarn build

      - name: Build
        run: yarn && yarn build
        working-directory: ${{ env.working-directory }}
