name: Storybook Deployment
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: storybook
    env:
      working-directory: ./docs
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build1
        run: yarn && yarn build:storybook

      - name: Build2
        run: yarn && yarn build
        working-directory: ${{ env.working-directory }}

      - name: Test
        run: echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}
